// ==UserScript==
// @name         Secret Desmos functions
// @description  Unlocks secret functions (top secret), they just don't work until you enable them in Mathquill
// @run-at       document-start
// @author       Naitronbomb
// @match        https://www.desmos.com/calculator*
// @match        https://www.desmos.com/geometry*
// @match        https://www.desmos.com/3d*
// @grant        none
// ==/UserScript==

let oldConf = Calc.controller.getMathquillConfig;

const allFunc = new Set("rtxsqpone rtxsqmone hypot logbase factorial polyGamma area perimeter pointDet pointDot pointPerp complexMultiply segment line ray vector vectorThreeD mathVector mathVectorThreeD vectorDisplacementAsPoint vectorThreeDDisplacementAsPoint basePointFromVector basePointFromVectorThreeD circle center radius arc arcCenter arcFirstPoint arcMiddlePoint arcThirdPoint arcOmega undirectedAngleMarker directedAngleMarker directedCoterminalAngle undirectedCoterminalAngle supplement directedAngleMarkerRawDelta undirectedAngleMarkerRawDelta directedAngleMarkerMultiplier undirectedAngleMarkerMultiplier polygonInteriorUndirectedAngles polygonInteriorDirectedAngles vertices segments scaleTangentTransformation scaleTangentPolygon scaleTangentSegment scaleTangentLine scaleTangentRay scaleTangentCircle scaleTangentArc scaleTangentDirectedAngleMarker scaleTangentUndirectedAngleMarker addTangentPolygon addTangentSegment addTangentSegmentThreeD addTangentLine addTangentRay addTangentVector addTangentCircle addTangentArc addTangentTransformation addTangentDirectedAngleMarker addTangentUndirectedAngleMarker segmentGlider segmentThreeDGlider lineGlider rayGlider circleGlider arcGlider polygonEdgeByParameter polygonGlider chooseNonIncidentPoint circleCircleIntersection circleArcIntersection circleLineIntersection arcCircleIntersection arcArcIntersection arcLineIntersection lineCircleIntersection lineArcIntersection lineLineIntersection lineFromSegment lineFromRay parallel perpendicular rawTransform rawTransformConj transformWithoutTranslation transformScaleFactor translation dilation rotation reflection compose inverse transformPoint transformSegment transformLine transformRay transformVector transformCircle transformArc transformPolygon transformAngleMarker transformDirectedAngleMarker distanceThreeD segmentThreeD triangle sphere argmin argmax upperQuantileIndex lowerQuantileIndex quartileIndex upperQuartileIndex lowerQuartileIndex normalcdf normalpdf binomcdf binompdf poissoncdf poissonpdf uniformcdf uniformpdf invT invPoisson invBinom invUniform tpdf tcdf invNorm normalSample uniformSample tSample poissonSample binomSample validateRangeLength validateSampleCount select sortPerm elementsAt uniquePerm restriction restrictionToBoolean".split(" "));

// Generated with:
// Object.values(Calc.controller.getMathquillConfig([])).map(x => x.split(' ')).flat().map(x => x.split('|')[0]).join()
// on respective https://www.desmos.com/[calculator type]
const regularCalc = new Set("exp,ln,log,total,length,count,mean,median,quantile,quartile,nCr,nPr,stats,stdev,stddev,stdDev,stdevp,stddevp,stdDevP,mad,var,varp,variance,cov,covp,corr,spearman,lcm,mcm,gcd,mcd,gcf,mod,ceil,floor,round,abs,min,max,sign,signum,sgn,sin,cos,tan,csc,sec,cot,sinh,cosh,tanh,csch,sech,coth,arcsin,arccos,arctan,arccsc,arcsec,arccot,arcsinh,arccosh,arctanh,arccsch,arcsech,arccoth,arsinh,arcosh,artanh,arcsch,arsech,arcoth,polygon,distance,midpoint,sort,shuffle,join,unique,erf,TTest,ttest,TScore,tscore,iTTest,ittest,IndependentTTest,normaldist,tdist,poissondist,binomialdist,uniformdist,pdf,cdf,random,inverseCdf,inversecdf,histogram,dotplot,boxplot,pdf,cdf,rgb,hsv,for,width,height,with,real,imag,conj,arg,det,inv,transpose,rref,trace,tone,for,with,ln,log,sin,sinh,arcsin,arcsinh,arsinh,cos,cosh,arccos,arccosh,arcosh,tan,tanh,arctan,arctanh,artanh,cot,coth,arccot,arccoth,arcoth,sec,sech,arcsec,arcsech,arsech,csc,csch,arccsc,arccsch,arcsch,alpha,beta,sqrt,theta,phi,rho,pi,tau,nthroot,cbrt,sum,prod,integral,percent,infinity,infty,cross,ans,frac,int,gamma,Gamma,delta,Delta,epsilon,zeta,eta,Theta,iota,kappa,lambda,Lambda,mu,Xi,xi,Pi,sigma,Sigma,upsilon,Upsilon,Phi,chi,psi,Psi,omega,Omega".split(","));
const geoCalc = new Set("exp,ln,log,total,length,count,mean,median,quantile,quartile,nCr,nPr,stats,stdev,stddev,stdDev,stdevp,stddevp,stdDevP,mad,var,varp,variance,cov,covp,corr,spearman,lcm,mcm,gcd,mcd,gcf,mod,ceil,floor,round,abs,min,max,sign,signum,sgn,sin,cos,tan,csc,sec,cot,sinh,cosh,tanh,csch,sech,coth,arcsin,arccos,arctan,arccsc,arcsec,arccot,arcsinh,arccosh,arctanh,arccsch,arcsech,arccoth,arsinh,arcosh,artanh,arcsch,arsech,arcoth,polygon,distance,midpoint,sort,shuffle,join,unique,erf,TTest,ttest,TScore,tscore,iTTest,ittest,IndependentTTest,normaldist,tdist,poissondist,binomialdist,uniformdist,pdf,cdf,random,inverseCdf,inversecdf,histogram,dotplot,boxplot,pdf,cdf,rgb,hsv,for,width,height,with,real,imag,conj,arg,det,inv,transpose,rref,trace,tone,segment,line,ray,circle,arc,vector,glider,parallel,perpendicular,center,radius,area,perimeter,start,end,angles,angle,directedangles,directedangle,coterminal,supplement,vertices,segments,intersection,strictintersection,translate,dilate,rotate,reflect,construction,points,lines,circles,arcs,polygons,rays,anglebisector,for,with,ln,log,sin,sinh,arcsin,arcsinh,arsinh,cos,cosh,arccos,arccosh,arcosh,tan,tanh,arctan,arctanh,artanh,cot,coth,arccot,arccoth,arcoth,sec,sech,arcsec,arcsech,arsech,csc,csch,arccsc,arccsch,arcsch,alpha,beta,sqrt,theta,phi,rho,pi,tau,nthroot,cbrt,sum,prod,integral,percent,infinity,infty,cross,frac,gamma,Gamma,delta,Delta,epsilon,zeta,eta,Theta,iota,kappa,lambda,Lambda,mu,Xi,xi,Pi,sigma,Sigma,upsilon,Upsilon,Phi,chi,psi,Psi,omega,Omega".split(","));
const calc3D = new Set("exp,ln,log,total,length,count,mean,median,quantile,quartile,nCr,nPr,stats,stdev,stddev,stdDev,stdevp,stddevp,stdDevP,mad,var,varp,variance,cov,covp,corr,spearman,lcm,mcm,gcd,mcd,gcf,mod,ceil,floor,round,abs,min,max,sign,signum,sgn,sin,cos,tan,csc,sec,cot,sinh,cosh,tanh,csch,sech,coth,arcsin,arccos,arctan,arccsc,arcsec,arccot,arcsinh,arccosh,arctanh,arccsch,arcsech,arccoth,arsinh,arcosh,artanh,arcsch,arsech,arcoth,polygon,distance,midpoint,sort,shuffle,join,unique,erf,TTest,ttest,TScore,tscore,iTTest,ittest,IndependentTTest,normaldist,tdist,poissondist,binomialdist,uniformdist,pdf,cdf,random,inverseCdf,inversecdf,histogram,dotplot,boxplot,pdf,cdf,rgb,hsv,for,width,height,with,real,imag,conj,arg,det,inv,transpose,rref,trace,tone,segment,triangle,vector,start,end,sphere,for,with,ln,log,sin,sinh,arcsin,arcsinh,arsinh,cos,cosh,arccos,arccosh,arcosh,tan,tanh,arctan,arctanh,artanh,cot,coth,arccot,arccoth,arcoth,sec,sech,arcsec,arcsech,arsech,csc,csch,arccsc,arccsch,arcsch,alpha,beta,sqrt,theta,phi,rho,pi,tau,nthroot,cbrt,sum,prod,integral,percent,infinity,infty,cross,ans,frac,int,gamma,Gamma,delta,Delta,epsilon,zeta,eta,Theta,iota,kappa,lambda,Lambda,mu,Xi,xi,Pi,sigma,Sigma,upsilon,Upsilon,Phi,chi,psi,Psi,omega,Omega".split(","));

const CALC = window.location.href.replace(/[http|https]:\/\/www\.desmos\.com\//, "");
const otherValues = CALC.startsWith("calculator") ? geoCalc.union(calc3D) : CALC.startsWith("geometry") ? regularCalc.union(calc3D) : regularCalc.union(geoCalc);
const opNames = " " + [...allFunc.difference(otherValues)].join(" ");

Calc.controller.getMathquillConfig = e => {
    let conf = oldConf.call(Calc.controller, e);
    conf.autoOperatorNames += opNames;
    // hypot(a,b) -> sqrt(a^2+b^2)
    // polyGamma(order, x)
    // rtxsqpone(x) -> sqrt(x^2+1)
    // rtxsqmone(x) -> sqrt(x^2-1)
    // validateSampleCount is, in the words of Naitronbomb, "screwd up"
    // sortPerm(a) -> sort([1...a.count], a) - 1
    // argmin(a) -> [1...a.count][a=a.min][1]
    // argmax(a) -> b[b.count] with b=[1...a.count][a=a.max]
    return conf;
}